language: php

php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Install grunt.
  - npm install -g grunt-cli bower

install:
  # install drush
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*
  - phpenv rehash

before_script:

  # Install Drupal
  - cp travis.config.sh config.sh
  - ./install -dy

  # Install client
  - cd client
  - npm install
  - bower install
  - cp config.travis.json config.json
  - grunt serve > ~/grunt.log 2>&1 &
  - cd ..

  # Install Behat
  - cd behat
  - cp aliases.drushrc.php ~/.drush/
  - cp behat.local.yml.travis behat.local.yml
  - composer install --prefer-source
  - cd ..

script:
  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  # start a web server on port 8080, run in the background; wait for initialization
  - drush @site runserver 127.0.0.1:8080 &

  # Wait for Grunt to finish loading.
  - until $(curl --output /dev/null --silent --head --fail http://localhost:9000); do sleep 1; echo '.'; done

  # Run phantomJs.
  - phantomjs --webdriver=4444 > ~/phantomjs.log 2>&1 &

  # Run behat tests.
  - cd behat
  - ./bin/behat --tags=~@wip

  # Print log ~/phantomjs.log
  - cat ~/phantomjs.log
